name: Publish Extension

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install pnpm
      run: |
        corepack enable
        corepack prepare pnpm@latest --activate
        export PNPM_HOME=$(pnpm config get prefix)/bin
        export PATH=$PNPM_HOME:$PATH

    - name: Install dependencies
      run: pnpm install

    - name: Install VSCE
      run: pnpm add -g @vscode/vsce

    - name: Publish to Marketplace
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
      run: vsce publish
